### ISSUE TITLE
GenICam_3_1_Basler_pylon is undefined and causes build error

### ISSUE THREAD

**Issue by tommishe** [basler/pylon-ros-camera#271]
### Issue description

Type GenICam_3_1_Basler_pylon is undefined and causes build error

### Code example about how to reproduce the issue

in pylon_ros2_camera_component/include/internal/impl/pylon_ros2_camera_base.hpp#L1485

catch (const GenICam_3_1_Basler_pylon::InvalidArgumentException& ex)

GenICam_3_1_Basler_pylon is undefined

### Error message

```shell
/home/tom/code/pylon_ws/src/pylon_ros2_camera/pylon_ros2_camera_component/include/internal/impl/pylon_ros2_camera_base.hpp: In member function ‘virtual bool pylon_ros2_camera::PylonROS2CameraImpl<CameraTraitT>::setUserOutput(const int&, const bool&)’:
/home/tom/code/pylon_ws/src/pylon_ros2_camera/pylon_ros2_camera_component/include/internal/impl/pylon_ros2_camera_base.hpp:1485:18: warning: ISO C++ forbids declaration of ‘GenICam_3_1_Basler_pylon’ with no type [-fpermissive]
 1485 |     catch (const GenICam_3_1_Basler_pylon::InvalidArgumentException& ex)
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~
/home/tom/code/pylon_ws/src/pylon_ros2_camera/pylon_ros2_camera_component/include/internal/impl/pylon_ros2_camera_base.hpp:1485:42: error: expected ‘)’ before ‘::’ token
 1485 |     catch (const GenICam_3_1_Basler_pylon::InvalidArgumentException& ex)
```

### Hardware setup description

AMDx64 
Basler acA1600-60gc

### Runtime information

```shell
Ubuntu 22.04 
ROS2 humble 
pylon info: 10.2.1.471 64-Bit
----------------------------------------
pylon Setup info: 8.1.0.16743 
----------------------------------------
pylon Application info: 4.0.2.16804 64-Bit
----------------------------------------
pylon Viewer info: 10.0.2.16804 64-Bit
----------------------------------------
Host system infos:

CPU architecture: x86_64
Kernel type: linux
Kernel version: 6.8.0-57-generic
OS type: ubuntu
OS version: 22.04
Render Backend: OpenGL
----------------------------------------
Screen(s):

Screen 0 scale factor: 1
Screen 0 resolution: 2560x1440
Screen 1 scale factor: 1
Screen 1 resolution: 1920x1080
----------------------------------------
Window(s):

"pylon Viewer 64-Bit" on screen 1
----------------------------------------
Host network infos:

Host network adapter enp0s31f6:
    Name: enp0s31f6
    MAC address: E8:6A:64:E3:4F:C0
    IP address: 10.100.30.131
    Subnet mask: 255.255.0.0
    IP address: 10.10.31.123
    Subnet mask: 255.255.255.0

Host network adapter wlp0s20f3:
    Name: wlp0s20f3
    MAC address: D4:3B:04:C1:53:D6
    IP address: 192.168.61.67
    Subnet mask: 255.255.224.0
```

### Is your camera operational with the Basler pylon Viewer on your platform?

Yes

**Comment by tommishe** [comment]
Commenting out this catch statement resolves build error

**Comment by cybrengineer** [comment]
I am getting the same error as well. If needed I can supply the docker image I am building the package in

**Comment by emulate-jonathanmanning** [comment]
Compiles OK against pylon 8.0.2 deb, humble branch fails with this error against pylon 8.1.0 deb.

A patch does seem as simple as using the generic "GenICam" alias instead of the longer alias, as recommended in the namespace documentation in [/opt/pylon/share/pylon/doc/BPD/files/pylonapi/cpp/namespace_gen_i_cam.html](https://docs.baslerweb.com/pylonapi/cpp/namespace_gen_i_cam#detailed-description)

```
-    catch (const GenICam_3_1_Basler_pylon::InvalidArgumentException& ex)
+    catch (const GenICam::InvalidArgumentException& ex)
```

**Comment by FrancoisPicardDTI** [comment]
Hello @tommishe @broccan @emulate-jonathanmanning 
This is now fixed. Thank you for the reporting and the fix. I am closing the issue.

**Comment by mjohenneken** [comment]
@FrancoisPicardDTI great thanks for the fix. We are still encountering this issue in jazzy branch, maybe more branches are affected?

**Comment by FrancoisPicardDTI** [comment]
Hi @mjohenneken 
It is now fixed both on jazzy and kilted.

**Comment by mjohenneken** [comment]
great, we finished work on the affected system in the meantime. Feel free to close the issue.
